### ISSUE TITLE
Julian Botta open source mechanical ventilator

### ISSUE THREAD

**Issue by dahifi** [PubInv/covid19-vent-list#1]
Not sure if this was added to the list or not: 
https://docs.google.com/document/d/1FNPwrQjB1qW1330s5-S_-VB0vDHajMWKieJRjINCNeE/edit

**Comment by RobertLRead** [comment]
It wasn't clear to me if this was a project, or a resource. Would you like it listed as a project? If so, is this URL best for it? I don't think you want an editable URL placed in a github repo.

**Comment by RobertLRead** [comment]
I added this.
