### ISSUE TITLE
Check Corovent project again, this may be news...

### ISSUE THREAD

**Issue by RobertLRead** [PubInv/covid19-vent-list#103]
Hello. I am from www.corovent.com - our group of biomedical engineers, ICU doctors, manufacturers and other pros has created a new medical ventilators for patients with the most severe course of Covid-19 disease. See the introduction and explanation video of our ventilator (https://youtu.be/kFM2FqaOhJE). Today we have passed all the necessary tests in official Czech testing authority and we are starting mass production - our ventilator is focused on the Covid patients only and is created from high tech valves/sensors ... for other industries in a way that its assembly resembles Lego, so we are able to produce it in very large quantities very quickly - our facility is optimized for few hundreds per day!
We are now looking for countries, that need our ventilators the most - so that we can start saving lives as quickly as possible. We can quickly adapt our ventilators for every country - the proper connectors for medical gasses, language, voltage etc. But we need in every country also government authorization for usage of non-medical device in hospitals (standard medical certification takes 6-18 months, we do not have time for that, although our device is designed the same way from the same people that do it last 25 years).
So if you know that your country need them and you can connect us with the proper people on government side, who could grant it and who could order it - let us know via contact-us form on our website.
YouTubeYouTube | CoroVent
(English subtitles) CoroVent - pulmonary ventilator for Covid-19 patients

D
Droplette is in this channel

**Comment by avinashbaskaran** [comment]
The openness, buildability, covid-19 suitability and clinicial friendliness has definitely improved, however, as is the case for several of such projects in the official certification stage, I can't find the specifications of their reliability (and to a degree, functional) testing and am having to give a low score without the details
