### ISSUE TITLE
Please add GitHub link to the Hackaday

### ISSUE THREAD

**Issue by hackadayrex** [PubInv/covid19-vent-list#11]
I see the Hackaday got rated poorly for openness and build-ability, sorry that wasn't the intension just forgot to post the link in the youtube page. 

Here are design and build instructions (including list of parts) so that others can learn from this design.
https://github.com/hackadayrex/ventilator

Great that there are so many options :)

**Comment by RobertLRead** [comment]
Thank you! I've bumped you up a bit. May I suggest you add a license to your repo if you are ready for that?
