### ISSUE TITLE
No link here, but maybe we can track this down....

### ISSUE THREAD

**Issue by RobertLRead** [PubInv/covid19-vent-list#114]
This link sounds interesting, but I didn't see an actual repo or even URL. Perhaps there is enough information to search for it?

https://worldindustrialreporter.com/a-low-cost-easy-to-build-ventilator-for-covid-19-treatment/?adsrc_=article2

**Comment by avinashbaskaran** [comment]
@RobertLRead 
Dr. Read,

This is in reference to a recent publication on the device: https://erj.ersjournals.com/content/early/2020/04/16/13993003.00846-2020.figures-only


There seems to be enough info to make an evaluation
