### ISSUE TITLE
Vacuum powered DIY Ventilator for consideration

### ISSUE THREAD

**Issue by kaiem** [PubInv/covid19-vent-list#116]
Hi, Great spreadsheet!

I've posted details of a DIY Ventilator to Github
https://github.com/kaiem/COVID-19_Ventilator_DIY_Prototype

Some ideas and building techniques may be useful to other projects.
The prototype is functional, however it is not complete. 

It comprises only 3D printed parts and household store items (no electronics).
Valving uses hard 3D printed components with no reliance on flexible membranes.
No need for Ambu bag, although could be incorporated if available.

**Comment by avinashbaskaran** [comment]
Hello!

Thank you for the request, we have added your project!
We want to better understand your goals and pain points in-order to help remove your roadblocks. We are starting with a short 4 hour virtual conference geared to support the maker community (on May 21st 2020). The theme of the conference is “Towards Cooperation in the Pandemic Mid-Game” would like to hear what topics interest you most. For the topics that we can't cover, we will try to publish resources after. Below is a short interest form regarding this event. Please respond in a day or two so we can have a little more time to line up there best speakers possible!

https://docs.google.com/forms/d/e/1FAIpQLScmguy1fMqwGqQAR3Is5Dsq-bxhVAGAoh8yI0gyqV4B6uvTtw/viewform?usp=sf_link
