### ISSUE TITLE
Add Fluxtronic Project

### ISSUE THREAD

**Issue by fluxtronic-medical** [PubInv/covid19-vent-list#117]
https://github.com/fluxtronic-medical/Fluxtronic

https://youtu.be/dyl--hyxr6U

**Comment by avinashbaskaran** [comment]
Hello!

Thank you for the request, we have added your project!
We want to better understand your goals and pain points in-order to help remove your roadblocks. We are starting with a short 4 hour virtual conference geared to support the maker community (on May 21st 2020). The theme of the conference is “Towards Cooperation in the Pandemic Mid-Game” would like to hear what topics interest you most. For the topics that we can't cover, we will try to publish resources after. Below is a short interest form regarding this event. Please respond in a day or two so we can have a little more time to line up there best speakers possible!

https://docs.google.com/forms/d/e/1FAIpQLScmguy1fMqwGqQAR3Is5Dsq-bxhVAGAoh8yI0gyqV4B6uvTtw/viewform?usp=sf_link
