### ISSUE TITLE
Please add Respirador-DQ3D-NICA

### ISSUE THREAD

**Issue by DQUEROL** [PubInv/covid19-vent-list#118]
I have developed yet another AMBU bag respirator (NOT VENTILATOR). It can be used in pre-clinical environments, like here in Nicaragua. Most of the parts are either recycled from printers or laser cut. Total cost should be under 150US.  It is free to use under creative commons non comercial license. 
Further info, plans and details (in spanish) at https://github.com/DQUEROL/Respirador-DQ3D-NICA
Thanks for distributing.
Daniel Querol

**Comment by avinashbaskaran** [comment]
Hello!

Thank you for the request, we have added your project!
We want to better understand your goals and pain points in-order to help remove your roadblocks. We are starting with a short 4 hour virtual conference geared to support the maker community (on May 21st 2020). The theme of the conference is “Towards Cooperation in the Pandemic Mid-Game” would like to hear what topics interest you most. For the topics that we can't cover, we will try to publish resources after. Below is a short interest form regarding this event. Please respond in a day or two so we can have a little more time to line up there best speakers possible!

https://docs.google.com/forms/d/e/1FAIpQLScmguy1fMqwGqQAR3Is5Dsq-bxhVAGAoh8yI0gyqV4B6uvTtw/viewform?usp=sf_link
