### ISSUE TITLE
Evaluate this paper which as been given FDA approval...

### ISSUE THREAD

**Issue by RobertLRead** [PubInv/covid19-vent-list#120]
This is an acedemic paper, not clear how open it is but apparently it has been given FDA Approval: https://arxiv.org/abs/2003.10405v1

https://scitechdaily.com/fda-approval-granted-for-simplified-ventilator-design-from-particle-physics-community/

**Comment by avinashbaskaran** [comment]
Dr. Read,

Interestingly, the paper includes a "License Agreement" section. While they detail their functional validation, I couldn't find any description of reliability testing, though I am sure such testing was put in place before FDA approval.
