### ISSUE TITLE
Go through FDA approval list and see if we should update any on our list...

### ISSUE THREAD

**Issue by RobertLRead** [PubInv/covid19-vent-list#123]
https://www.fda.gov/media/136528/download

I just became aware that the FDA is publishing that list; most of them are not open, but let's run through it as a cross-reference.  The MVM seems to be on the list, for example.

**Comment by avinashbaskaran** [comment]
In my discussions with the Fraunhofer team, it seems they intend to help incorporate this data into the spreadsheet
