### ISSUE TITLE
Add project Tetra a ventilator splitter

### ISSUE THREAD

**Issue by Judoguy12** [PubInv/covid19-vent-list#132]
Please can Project Tetra be added to the vent list which is a ventilator splitter system
Project overview: 
https://tetrabiodistributed.github.io/docs/explanations/overview/
Github: https://github.com/helpfulengineering/project-tetra
Questions email: jrwjudo@gmail.com

**Comment by RobertLRead** [comment]
I think we should create a new Tab for this class of device.

**Comment by Judoguy12** [comment]
Yeah probably, it does not fit with a true ventilator

**Comment by avinashbaskaran** [comment]
Thank you very much for this issue, I've added in into a "ventilator augmentation" tab. This location may be temporary, but the project has been added nonetheless!
