### ISSUE TITLE
Updates Respirador DQ3D-NICA

### ISSUE THREAD

**Issue by DQUEROL** [PubInv/covid19-vent-list#137]
Main changes from May 22 to June 14:
The machine was tested by the local Ventilator provider (BuehlerPharma) and passed the basic tests https://www.youtube.com/watch?v=ZXE7Wcpd6EI . 

A series of improvements in the management of pressure are described [here](https://github.com/DQUEROL/Respirador-DQ3D-NICA/blob/master/06%20Revisiones%20y%20Testing/Factores%20relacionados%20con%20la%20presi%C3%B3n%20Respirador%20DQ3D%20NICA.docx) , including PEEP and firmware pressure management.

Firmware was modified to continue operation even while certain warning alarm are triggered, and can be reset on the fly. Also, every cycle the machine checks its status, and recalibrates if needed.

4 machines have been built until now, and I have been looking for 7,000US in order to build 10 more and cover the prior expenses, but to no avail. I am waiting for Robert Reed´s sensor.

**Comment by avinashbaskaran** [comment]
Thanks again Daniel, please let me know as any changes arise!
