### ISSUE TITLE
Link to A Super-simple Guide to Mechanical Ventilation... is incorrect

### ISSUE THREAD

**Issue by psifi57** [PubInv/covid19-vent-list#14]
Hi,

The link goes to a different (tho interesting) document...

Looking forward to this guide!
Christine

A Super-simple Guide to Mechanical Ventilation For Open Source Engineers Designing Ventilators for the COVID-19 Pandemic -- This was written by me (Robert L. Read). It's my best attempt at an introduction.

**Comment by RobertLRead** [comment]
Fixed: [https://docs.google.com/document/d/1p-oYUv_6FadipV67g2O5yfnQvpdvZDm4WadYVubhoH4/edit?usp=sharing](https://docs.google.com/document/d/1p-oYUv_6FadipV67g2O5yfnQvpdvZDm4WadYVubhoH4/edit?usp=sharing)
