### ISSUE TITLE
New Project UCSD MADVent Mark V

### ISSUE THREAD

**Issue by jake653** [PubInv/covid19-vent-list#143]
The UCSD MADVent Mark V became available in June
It's a bag squeezer driven by a stepper motor, with detailed test lung data.

http://friend.ucsd.edu/madvent/  DL links just below the detailed CAD drawing, half way down the page.
https://onlinelibrary.wiley.com/doi/full/10.1002/mds3.10106   academic paper 05 June 2020
https://ucsdnews.ucsd.edu/pressrelease/COVID19ventilator   news fluff

**Comment by avinashbaskaran** [comment]
Thank you very much for raising this issue, The UCSD MADVent Mark V has been added
