### ISSUE TITLE
 Retrovent19  Another Candidate an Update of the classic Bird Mark 7

### ISSUE THREAD

**Issue by jake653** [PubInv/covid19-vent-list#144]
https://www.retrovent19.com/   
 
April 01, 2020 announcement with .step file DL Link     (above page links here)
https://nsri.nebraska.edu/newsandevents/newsreleases/team-redesigns-bird-mark-7-respirator-for-surge-emergency-manufacturing

Using the Bird Mark 8 as a ventilator
https://www.youtube.com/watch?v=SG3zlpRSfWE   

has an empty archived Github Depository

CAD Designer discussion with nice Mark-7 photo and Mk7 service manual links.
https://forum.freecadweb.org/viewtopic.php?f=8&t=44912  

Deep in the weeds biography of the original designer
https://en.wikipedia.org/wiki/Forrest_Bird

**Comment by avinashbaskaran** [comment]
Thank you for this issue, I have added this vent!
