### ISSUE TITLE
Links added for previously mentioned 7 addition candidates

### ISSUE THREAD

**Issue by jake653** [PubInv/covid19-vent-list#145]
Not in spreadsheet candidates, and revisions, Links Added

Emergency Ventilator "DIEGO" bag squeezer "gravity operated by weight stack, lifted by cam
https://www.iit.it/iit-vs-covid-19/diego-ventilator
Source Files  https://zenodo.org/record/3859930#.XwWa8_JlBTY

This Coronavirus Ventilator Runs on Raspberry Pi, but Must Pass Tests in Colombia Before Use
https://interestingengineering.com/this-coronavirus-ventilator-runs-on-raspberry-pi-but-must-pass-tests-in-colombia-before-use
  https://github.com/Mascobot/pandemic-ventilator-2.0    w/  single file Arduino code
  
  
The Winnipeg Ventilator 1990s design updated,  Open Licence
"will support international groups looking to license this design to address the needs in their respective territory or region"
https://thewinnipegventilator.com

*Ferrari FI5 air powered  stm32  RTOS, HAL, graphics, C++ utilities
COVID-19: Ferrari develops pulmonary ventilator - the FI5 - open source  Air Powered
  "The technical specification of FI5, the drawings, the firmware, software and list of components are now available as an open source project, 13 May 2020"
https://www.ferrari.com/en-CA/formula1/articles/scuderia-ferrari-and-italian-institute-of-technology-present-fi5
Press:  https://corporate.ferrari.com/en/scuderia-ferrari-mission-winnow-and-italian-institute-technology-present-fi5
Source links  https://www.iit.it/iit-vs-covid-19/fi5-ventilator
               https://github.com/icub-tech-iit/ventilator-FI5
               Controller implemented in Simulink  IDLE, CPAP, VCV, PRVC
             stm32  RTOS, HAL, graphics, C++ utilities
         https://www.youtube.com/watch?v=aJfvRJYfhZw
       
         
Project Omnis - https://outerreeftech.com/pages/ventilator
   https://github.com/jazevedo/Omnis    Arduino code; PID motor control? & Android app
   
   
Kahanu | The Breath - Open Source Emergency Use Only, Unapproved Medical Device
https://kahanu.org/    bag squeezing cam

MPS Open Source Ventilator Design Files - need login to DL, Arduino, no source mentioned
https://www.monolithicpower.com/en/mps-open-source-ventilator
https://www.monolithicpower.com/mps-open-source-ventilator-design-files.html

**Comment by avinashbaskaran** [comment]
Thank you very much for this comment, I have added/updated entries per your suggestions
