### ISSUE TITLE
MPS (MIT inspired) project still being updated last on 6/15/20

### ISSUE THREAD

**Issue by jake653** [PubInv/covid19-vent-list#152]
Just wanted to make the general comment re their having a longer life than many of the open src vents.  They have 10 minutes of video somewhat instructive, also went to 70W motor and changed gearing to address low volume a lung simulator test revealed.
   Controller code added to 6/5 downloads update, but you have to sign up to access files.

**Comment by avinashbaskaran** [comment]
Thank you very much for this comment, I've added it as a note on the far right hand side of the spreadsheet
