### ISSUE TITLE
Are CPAPs included?  Mercedes F1 HPP, University College London (UCL) 

### ISSUE THREAD

**Issue by jake653** [PubInv/covid19-vent-list#153]
Free Use Licence
A breathing aid developed by engineers at Mercedes HPP, engineers at University College London (UCL) and clinicians at UCL Hospital has now been approved for use by the UK's National Health Service in the battle against coronavirus.

The designs of a new breathing aid developed by engineers at UCL and Formula One working with clinicians at UCLH have been made freely available to support the global response to Covid-19
https://www.ucl.ac.uk/news/2020/apr/designs-life-saving-breathing-aid-are-made-freely-available

UCL-Ventura breathing aids for Covid-19 patients
https://www.ucl.ac.uk/healthcare-engineering/covid-19/ucl-ventura-breathing-aids-covid-19-patients

** UCL-Ventura breathing aid (CPAP) – Design and manufacturing package
https://covid19research.uclb.com/product/ucl-cpap

**Comment by avinashbaskaran** [comment]
Thank you very much for this suggestion, I've added the device to the spreadsheet
