### ISSUE TITLE
Not Listed:  Open-AirVentGT

### ISSUE THREAD

**Issue by jake653** [PubInv/covid19-vent-list#154]
Another pneumatically compressing a BVM, with a backstory of a Georgia Tech Engineer Husband and Doctor wife teaming up.

**Open-AirVentGT** Used two sensors and a Raspberry Pi driving a computer monitor.
The University write-up and demo video page **Doesn't seem to have ** a public **source** file depository.  There is only a phone# and Email for the Medial Relations author of the article.  jtoon@gatech.edu
_"The team is reviewing how best to release the design for others to mass produce these devices to meet the global needs."_
https://rh.gatech.edu/news/634789/open-airventgt-emergency-ventilator-provides-patient-monitoring-feedback-control

Line so many others projects, it seem to have gone silent since the initial April 27, 2020 prototype announcement...Sorry if I overlooked criteria.

**Comment by avinashbaskaran** [comment]
Thank you very much for the update, I've added the project!
