### ISSUE TITLE
Please add RED Ventilator to your list

### ISSUE THREAD

**Issue by mgurunathan** [PubInv/covid19-vent-list#162]
Hello, we have an emergency ventilator project that I would like to have added to your master spreadsheet.  Our project is called "Respiratory Emergency Device (RED)", or "Project RED".  We are located on the web at https://redventilator.org .

Our project was started in early April and we are a group of engineers who have 5 years of previous ventilator design experience.  We are designing a blower based ventilator which will be manufacturable for under $4K.  It will provide many features seen in more expensive ventilators.  We plan to have a small number of prototypes ready by end of September.  Also, we have formed partnerships with teams in Nepal, India and Argentina who are interested in mass producing our design for their citizens.

FYI, many of the projects on your spreadsheet are based on the robotic squeezing of an ambu-bag.  We believe that most - if not all - of these projects, although created by well intentioned and creative individuals, are nevertheless going to be more or less ineffective.  In our 5 years working on a ventilator design prior to the COVID pandemic, we learned that mechanical ventilation is far more complex than apparent to the lay person.  We started our project (a non-profit) to try to put the knowledge we gained to good use.

Also:  our project is NOT an open source project.  Again, we don't believe everyone in the world is qualified to develop or manufacture life support equipment.  Therefore, we are carefully vetting the folks who are allowed to work on our project, and we will license the final design to individuals/organizations who can demonstrate the ability to properly manufacture the design.

Point of contact for the project is:

Mohan Gurunathan
mohan@redventilator.org

Please let me know if you have any questions.  Thanks!

Mohan

**Comment by avinashbaskaran** [comment]
Mr. Gurunathan,

Thank you very much for this update, and apologies for our delay in adding this item. We would like to include ranking data regarding the categories available here (https://docs.google.com/document/d/e/2PACX-1vRl9yZ27KvslftcNvweHgH1A81pO8gHL62TWpY_VY-UELWdK9x-4-3hNw3DbkemClzExPsg8RfnxilP/pub), could you please provide some background on your group's device?

**Comment by mgurunathan** [comment]
Hi @avinashbaskaran ,

Here are my rankings for our project:

Openness
4.	Has a clear license strategy, regular updates to plans

Buildability
4.	Complete documentations suggested reproducibility


Community Support
3.	Responsive leader or manager, more than one volunteer

Functional Testing
 0.  In Design Phase, Not listed/tested

Reliability Testing
 0.   Not Listed


COVID-19 Suitability   
0.  In design phase/Not listed

Clinician Friendly
3.	Breath rate, volume and pressure control easy to set, standard ports, clear external labeling graphically and in the language of choice


EMC (Electromagnetic compatibility) Testing
1.	In Design Phase, Not listed/tested/addressed


National Approval Agency/ EUA approvals
0.   Not listed/tested/addressed


Usage in field
      0.        
1.	Not deployed

Financing
1.	Blocked by need for investment

Manufacturability (1000s)
0. Insufficient plans to duplicate a single unit.

Manufactured Products/ produced products/ produced units
1.	Manufacturing planning in progress 


Please let me know if you require any other information.  Thanks.

Mohan

**Comment by avinashbaskaran** [comment]
Thank you very much, Mohan!
