### ISSUE TITLE
Cuirass type ventilator

### ISSUE THREAD

**Issue by jps2000** [PubInv/covid19-vent-list#20]
here is another link you may like to add
https://github.com/jps2000/Cuirass-Ventilator

**Comment by RobertLRead** [comment]
I have added it. It is difficult for me to evaluate clinical suitablity. You do not have a license  statement; may I suggest CC0 for desgins and GPL 3 for code? Get back to me if you make a change. Thanks for your efforts!

**Comment by RobertLRead** [comment]
Would you like to offer an email for us to add to our public spreadsheet as a point-of-contact?

**Comment by jps2000** [comment]
Contacts should be handled via https://github.com/jps2000/Cuirass-Ventilator / Issues
License added
I do not understand the criteria of judgements of categories. 
I think it is a very suitable concept for third world because it does not rely on intubation and uses everywhere available parts - creativity  pre-supposed. It is also the most lung  and circulation protective method as it mimics most natural breathing. I say this because I have expertise in designing  ventilators for veterinary use
https://www.researchgate.net/profile/Johannes_Schramel

**Comment by jps2000** [comment]
@ RobertLRead 
Just added a cuirass construction  designed with F360. f3d File is included  !!!!!
