### ISSUE TITLE
A breath challenge with MunichRe and Frauenhofer

### ISSUE THREAD

**Issue by ezintz** [PubInv/covid19-vent-list#23]
Hello everyone,

I am working at innosabi. We've launched together with MunichRe and Fraunhofer the challenge "Give a Breath". It is a global call for ideas and collaboration to identify the best 3D printable designs to enable the immediate, decentralized production of emergency equipment. The challenge includes funding for prizes and realization in sum of 1 million euros.

Could you please update the document about the possibility to submit designs in this challenge and to get funding for the realization? We would love to win your support in this. If you have ideas for partnerships we would love to connect you to our partners at MunichRe.

https://give-a-breath-challenge.innosabi.com/

All the best from Munich,
Eddy

**Comment by RobertLRead** [comment]
Done.
