### ISSUE TITLE
OpenVentilator - PopSolutions is listed twice - each listing has different details & score?!

### ISSUE THREAD

**Issue by JedMeister** [PubInv/covid19-vent-list#24]
As per subject line, the OpenVentilator project (via PopSolutions) is listed twice and the listings have inconsistent scores:

1. "OpenVentilator (PopSolutions)" - URL: https://www.popsolutions.co/en_US/openventilator - score: 2.79
2. "OpenVentilator-Popsolutions" - URL: https://github.com/popsolutions/openventilator - score: 2.43

**Comment by RobertLRead** [comment]
Fixed, than you.
