### ISSUE TITLE
Missing articles list

### ISSUE THREAD

**Issue by neilmartis** [PubInv/covid19-vent-list#3]
https://onlinelibrary.wiley.com/doi/full/10.1111/j.1365-2044.2009.06207.x

https://onlinelibrary.wiley.com/doi/pdf/10.1197/j.aem.2006.05.009

https://www.npr.org/sections/health-shots/2014/01/03/259436844/saving-babies-lives-starts-with-aquarium-pumps-and-ingenuity

https://www.medicaldesignandoutsourcing.com/low-cost-ventilator-wins-sloan-health-care-prize/

https://digitalcommons.usu.edu/cgi/viewcontent.cgi?referer=https://www.google.com/&httpsredir=1&article=1016&context=spacegrant&fbclid=IwAR1EtJVcxXm82PjGWFCA0t7H_MxNVjuseAePRfxNORr9h4ZQLQ9sNdQjXhc

http://hadleighhealthtechnologies.com/pumani-bcpap/

https://3dprint.com/45352/3d-printed-ventilator-manifold/

https://docs.google.com/document/d/1uF6VbxwtKA2iuQtYNQJ-yW9clQXDOgtaTS5TvQ8Sk8k/edit?fbclid=IwAR2T3zy5GTK5u6BFtXpogwAUY-BNTEdF00nK-jUKaXJz988wi2QHxVS8CoY

https://www.allegrosafety.com/product/lp-full-mask-supplied-air-respirator/

**Comment by RobertLRead** [comment]
Thank you!  I have sorted through these and put some in resources and some in projects.
