### ISSUE TITLE
Comment cells not fully readable (cells too small, not clickable with public view link)

### ISSUE THREAD

**Issue by Jaribeau** [PubInv/covid19-vent-list#43]
Thanks again for all of the work on this!

The link to the spreadsheets (the pubhtml style link) does not allow clicking on a cell to view the contents as a typical spreadsheet view does. This means that the comment cells (and long project names) are unreadable past the first few words.

Would be great to just have a standard, read-only spreadsheet link. Allowing the public to add suggestions via Google Sheets Comments could also be a good way to get help from the public in keeping things updated.

Cheers!

**Comment by RobertLRead** [comment]
You are correct. For a while it didn't matter. I have made it standard commentable link.
