### ISSUE TITLE
Buildability criterai should take care of components availability

### ISSUE THREAD

**Issue by cquest** [PubInv/covid19-vent-list#46]
A lot of ventilator depend on some medical subparts (like ambubag).

Currently most medical components lack after a few weeks.
Buildability should take this into account.
Designs with no medically linked parts are in fact more "buildable" in mass.

**Comment by RobertLRead** [comment]
I'm not sure I agree that no medical parts is always better, it depends on the part. I've added a new column, (manufacturability 1000s) based on these criteria:

Manufacturability (1000s)

Note: This is usually zero until Buildability of (1) unit (separate column) reaches 4.


 0. Insufficient plans to duplicate a single unit.
1. Bill of Materials (BOM) clear.
2. 2d parts, 3d parts, code, all clearly documented.
3. Electrical schematics and air circuit schematics clear. PCBs if any present and documented. Wiring if required fully documented.
4. Basic instructions and special instructions present. Video instructions helpful. Documented in language of choice, preferable more than one. Basic description of “smoke tests” and simple quality assurance present.
5. Either evidence of BOM availability in units of 1000, or supply-chain flexibility of parts suggesting same. Documentation for handling supply-chain disruption present if minimal. Plans include manufacturing issues for non-expert workers. Detailed quality assurance plans present.


Hopefully that captures what you are getting at.
