### ISSUE TITLE
VentilAid

### ISSUE THREAD

**Issue by niutech** [PubInv/covid19-vent-list#5]
Engineers and designers from Poland-based Urbicum have banded together to launch the [VentilAid](http://www.ventilaid.org) project, an effort to design an open-source ventilator which can be reproduced using a 3D printer and an assembly of basic, easily accessible parts. The open-source ventilator is being designed to help medical professionals in the fight against the coronavirus pandemic in cases where more traditional hospital resources are limited or exhausted.
Could you please add it to the list?

**Comment by RobertLRead** [comment]
Thank!

I've added this:

[VentilAid](https://www.ventilaid.org/)

Current prototype is pneumatic. 3D printed parts complete, but I can't find complete assembly instructions. They are working on a second electric prototype.

* * *
If you can find me a link to more complete assembly instructions in your GitLab, I'll change it.
