### ISSUE TITLE
Open Ventilator Remote Monitoring Project

### ISSUE THREAD

**Issue by samcervantes** [PubInv/covid19-vent-list#58]
The goal of our project is to provide a single dashboard interface to remotely monitor multiple ventilators at once. Check out our [Live Demo](http://www.ventilatormonitor.com) and [Github Repo](https://github.com/Open-Ventilator-Remote-Monitoring/docs/wiki). Please submit an issue on our Github repo to discuss software integration with you ventilator design. Priority is given to ventilator design teams who are closest to manufacturing.

**Comment by RobertLRead** [comment]
Added under Systems for Multiple Patients.
