### ISSUE TITLE
Non-electric ventilator design 

### ISSUE THREAD

**Issue by jety89** [PubInv/covid19-vent-list#62]
Pretty awesome, pressure-operated valves with some tubing.
https://www.youtube.com/watch?v=y_aHpr81ASk

Please indicate if this is not the appropriate channel to share.

**Comment by jety89** [comment]
https://www.vortran.com/go2vent

https://www.youtube.com/watch?v=afFWwEcIBW4
VORTRAN Automatic Resuscitator (GO2VENT) Training
Vortran Medical Technology 1, Inc.

**Comment by jety89** [comment]
Looks like the closest analog is the gtech open-source ventilator

**Comment by jevillacres** [comment]
Thanks for sharing! I added the device to the spreadsheet - although it is not open source, i've seen one other group that based their design off of it. Here's the link in case you're interested: https://docs.google.com/document/d/1R25O2mKT3TfSjXTmheGEevIk6rTJ49o-sGCJU3QqP3M/edit#

**Comment by jety89** [comment]
Awesome
