### ISSUE TITLE
Evaluate this Crowdsourced Ventilator Covid-19

### ISSUE THREAD

**Issue by RobertLRead** [PubInv/covid19-vent-list#63]
They have a nice video.  

crowdsourced-ventilator-covid-19

https://github.com/Crowdsourced-Ventilator-Covid-19/crowdsourced-ventilator-covid-19

**Comment by RobertLRead** [comment]
He said use: chuck.tung@gmail.com as a contact email.

**Comment by jevillacres** [comment]
Processed!
