### ISSUE TITLE
consider evaluating DRM127 as benchmark

### ISSUE THREAD

**Issue by bthestranger** [PubInv/covid19-vent-list#67]
The DRM127 is a prototype ventilator developed in 2011 by Freescale Semiconductor (NXP) engineers to highlight the capabilities of the Coldfire MCU. Although this project is not open-source, the available documentation, source code, and bill of materials is readily digestible as a smaller scale completed project. 

How does the this device compare to the amalgamation of new open-source projects?

document: https://www.nxp.com/docs/en/application-note/DRM127.pdf
thread with hardware and software source: https://community.nxp.com/thread/501945

**Comment by jevillacres** [comment]
From what I could tell, it's functionally comparable to some of the better projects. Since it's not open-source, replicating it would take some guesswork, but is otherwise a great resource. Thanks!
