### ISSUE TITLE
Fluidic Ventilator

### ISSUE THREAD

**Issue by alwayslearningsomethingnew** [PubInv/covid19-vent-list#73]
Project(s) to analyze.

The concept is to utilize a fluidic ventilator design (based on circa 1960s era technology) to fill critical needs if there is a shortage of ventilators.  The technology is already incorporated into some commercially available ventilators.  

The designs listed below are "emergency" use versions of fluidic ventilators that have been simplified to their basic forms.  

https://3dprintingindustry.com/news/volunteers-develop-3d-printable-ventilator-based-on-1965-u-s-army-design-170653/

https://3dprint.nih.gov/discover/3DPX-013664

They are relatively simple designs that can be mass produced via various manufacturing means (i.e. injection molding, etc)

**Comment by avinashbaskaran** [comment]
@alwayslearningsomethingnew , Thank you for the suggestion! We have included the ARMEE Vent fluidic ventilator design (http://45.79.18.170)
