### ISSUE TITLE
High quality project worth evaluating

### ISSUE THREAD

**Issue by Jaribeau** [PubInv/covid19-vent-list#80]
https://jmawireless.com/prevail-ny/

Couple of quick notes:
- Open access to cad files, schematics, code, manuals, assembly instructions
- High quality, very buildable design
- Contacted them regarding the testing they have/intend to complete. Will report back if I ear anything interesting on this front.

**Comment by RobertLRead** [comment]
I think this is line #13 on the list already.

**Comment by Jaribeau** [comment]
You're right - somehow I missed that. Cheers.
