### ISSUE TITLE
Reporting a New Group Working on Ventilators

### ISSUE THREAD

**Issue by pbcelis** [PubInv/covid19-vent-list#87]
Hi! 

My name is Pedro Celis. I am a professor at Simón Bolívar University in Caracas, Venezuela. 

We have managed to form a group of professionals from multiple disciplines (lots of engineers and medical doctors among them), in order to create the first low cost, locally made, ventilator in Venezuela, to help people with COVID-19. Venezuela has no more than 400 operational ventilators, and we expect that around 4,000 would be needed at the peak of the pandemic in order to save lives. 

We are taking advantage of work done around the world in this regard. We are working on a electro-mechanical device such as the one propose by the israelis. We are also developing another electro-pneumatic one. The most difficult part is to find parts and components in the country, so we have to redesign what is out there in order to adapt to what we may find.

Our group effort is called "Respirador Venezolano" - (Venezuelan Ventilator)

My assessment of the attributes on the list are as follows:
Openness: 2
Buildability: 1
Community Support: 4
Functional Testing: 0
Reliability Testing: 0
COVID-19 Suitability: 0
Clinician Friendly: 0
Average: 1

_Manufacturability: 0
Date Last Evaluated: April 15th 2020
Point of Contact: pbcelis@usb.ve & ftorre@usb.ve
Needs: a lot. Specially electronic components and measuring devices
Drive: We are working on a mechanical device to pressure the AmbuBag (MIT like) and another using pneumatic pressure from air/oxygen line.
It is a device done with what we may find available, which is scarce.
Language is spanish._

We have a group of more than 25 people, volunteers, working round the clock to develop a working prototype, so that we can test it, and get the sanitary permit so that we may mass produce it. We started working on March 31st 2020. We are working on a web page. We are using Google Drive as a repository of files, and Slack to coordinate efforts. We also have an Instagram account, and we are developing a twitter and a facebook one.  Instagram account is here: 
https://www.instagram.com/p/B-n3SiaHEOY/?igshid=laz6eje29rm2 

Thanks!!!

**Comment by RobertLRead** [comment]
Thank you. I have added it. Good luck; let us know how we can help you and people of Venezuela. Send us issues as you make progress.
