### ISSUE TITLE
UK Ventilator Crowd - Open Source ventilator project

### ISSUE THREAD

**Issue by entelecheia1963** [PubInv/covid19-vent-list#9]
Folks, We are very happy to hear that there are a large number of open-source ventilator projects! Would you please add ours to your list. The 'public' website is here: https://www.ventilatorcrowd.org/ 

This is supported by a back-end, Slack site for collaboration. Anybody can join this .. just request and I can send out an invitation.

We are also publishing analaysis here: https://github.com/ventilatorcrowd/Ventilator-Crowd 

We would particularly like to draw other team's attention to our analysis of the UK governement MHRA 'Specification' (actually, a rather badly written 'User Requirement Document'. Our Systems Engineering work on this may help other teams.

Good work guys and best of luck.

**Comment by RobertLRead** [comment]
Done, thank you. I have signed up at your site.
